### ISSUE TITLE
Safari: 'Deze verbinding is niet prive'

### ISSUE THREAD

**Issue by yochem** [ieni/website#1]
**Safari** v11.0.2 (13604.4.7.1.3) op **macOS** v10.13.2 (17C88) geeft de volgende melding bij het bezoeken van https://ieni.org:

![certificaat foutmelding](https://user-images.githubusercontent.com/23235841/37566982-9fa79a62-2ac0-11e8-888a-65c51c2baf69.png)

Misschien een ongeldig certificaat?

**Comment by lesander** [comment]
Hi Yochem. De nieuwe website staat nog niet live, wat je ziet is de "oude" website welke inderdaad geen geldig SSL certificaat (meer) heeft. Hier heb ik geen invloed op.

**Comment by moorlag** [comment]
er komt een nieuw certificaat


Met vriendelijke groet / with kind regards,

Ramon Moorlag
about.me/moorlag

2018-03-18 15:39 GMT+01:00 Sander Laarhoven <notifications@github.com>:

**Comment by lesander** [comment]
@yochem bedankt voor je issue. De website van deze repository staat nu online op https://ieni-beta.laarit.nl. Als je nog opmerkingen hebt of iets tegen komt horen we het graag! 😃
